[project]
name = "trainycorn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.15"
dependencies = [
    "mediapipe>=0.10.20",
    "opencv-python>=4.11.0.86",
    "typer>=0.15.1",
]
